version: 2
jobs:
  build:
    docker:
    - image: circleci/node:6.11.2
    steps:
    - run: sudo apt-get remove optipng
    - run: npm install -g yarn bower grunt-cli
    - run: yarn install
    - run: bower cache clean
    - run: bower install
    - run: bundle install

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build