version: 2
jobs:
  build:
    working_directory: ~/Branch-Example-Deep-Linking-Branchster-Web
    docker:
      - image: circleci/node:6.11.2
    environment:
      DC2: true
      BRANCH_STACK: node
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - checkout
      - run: sudo apt-get remove optipng
      - run: npm install -g yarn bower grunt-cli
      - run: yarn install
      - run: bower cache clean
      - run: bower install
      - run: bundle install
  deploy:
    docker:
      - image: circleci/node:6.11.2
    steps:
      - run: sudo pip install awscli
      - run: aws s3 cp dist/ s3://branch-cdn/branchster-angular/ --recursive
      - run: aws configure set preview.cloudfront true
      - run: aws cloudfront create-invalidation --distribution-id E10P37NG0GMER --paths /branchster-angular/*

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: [master]
