version: 2
jobs:
  build:
    docker:
    - image: circleci/node:6.11.2
    steps:
    - run: sudo apt-get remove optipng
    - run: npm install -g yarn bower grunt-cli
    - run: yarn install
    - run: bower cache clean
    - run: bower install
    - run: bundle install
  deploy:
    - run: sudo pip install awscli
    - run: aws s3 cp dist/ s3://branch-cdn/branchster-angular/ --recursive
    - run: aws configure set preview.cloudfront true
    - run: aws cloudfront create-invalidation --distribution-id E10P37NG0GMER --paths /branchster-angular/*

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: [master]
